name = "runpod-youtube-scraper"
main = "src/index.ts"
compatibility_date = "2024-03-20"

# Note: YOUTUBE_API_KEY and SLACK_WEBHOOK_URL should be set as secrets
# using `wrangler secret put YOUTUBE_API_KEY` and `wrangler secret put SLACK_WEBHOOK_URL`
[vars]
# Required: Your YouTube search query
SEARCH_QUERY = "runpod"
# Optional: Max results per YouTube API call (default 10)
MAX_RESULTS = "10"
# Optional: Hours within which a video is considered "Brand New" (default 24)
NEWNESS_WINDOW_HOURS = "24"

[[kv_namespaces]]
# Required: Binding name for KV storage
binding = "SEEN_VIDEOS"
# Required: Replace with your KV Namespace ID created via `wrangler kv namespace create seen_videos`
id = "YOUR_KV_NAMESPACE_ID"
# Required: Replace with the same KV Namespace ID for local preview
preview_id = "YOUR_KV_NAMESPACE_ID" 